server:
  port: 7643

database:
  host: 192.168.0.104
  port: 5432
  user: postgres
  password: yourpassword
  dbname: cosine2api
  sslmode: disable

upstream:
  base_url: https://api.cosine.sh

linuxdo:
  client_id: yourclientid
  client_secret: yourclientsecret
  backend_base_url: "http://127.0.0.1:7643"

jwt:
  secret: "your_jwt_secret_key_here"
