server:
  port: 7643

database:
  host: 192.168.0.104
  port: 5432
  user: postgres
  password: cao1411595711
  dbname: cosine2api
  sslmode: disable

upstream:
  base_url: https://api.cosine.sh

linuxdo:
  client_id: w0XW95nAehZXLzHcSid9hnX3mGwKZjt2
  client_secret: 6YjGbWluZnhJWaojcFzKFKsAomSnZ07T
  backend_base_url: "http://172.20.51.232:7643"

jwt:
  secret: "your_jwt_secret_key_here"
